summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2 
bin-url: https://github.com/leleliu008/uppm-package-repository-openbsd-7.3-amd64/releases/download/2025.07.25/pkg-config-0.29.2-openbsd-7.3-amd64.release.tar.xz 
bin-sha: e1818fc7cec20e5a398c1f5aaa25f8430a7255398ecf98260edb3894ce45208f
